language: node_js
node_js:
  - "7.10"
  - "8"
  - "9"
  - "node"
after_script: "npm install coveralls@latest && jest --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"